# Dependencies
#markdown:         redcarpet
#highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Dialvive
tagline:          "Another software developer's blog"
description:      'A nerdy, foodie, software developer.'
url:              https://dialvive.dev
baseurl:          ""

plugins:          [jekyll-paginate]

author:
  name:           'Diego Villalpando'
  url:            https://www.linkedin.com/in/diegovillalpando/

paginate:         5

# Custom vars
version:          2.0

github:
  repo:           https://github.com/Dialvive/dialvive.dev
