---
title: Diego Villalpando
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
enforce_ssl: dialvive.dev
highlighter: rouge
livereload: true
lsi: false
markdown: kramdown
port: 3000
url: https://dialvive.dev
permalink: /blog/:year/:month/:day/:title
owner:
  name: Diego Villalpando
  login: dialvive
  email: dialvive@protonmail.com
